version: '3'

services:
    web:
        build: .
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db
        environment:
            POSTGRES_CONNECTION_STRING: "Host=db;Database=aloha;Username=aloha;Password=aloha"
    db:
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "aloha"
            POSTGRES_USER: "aloha"
            POSTGRES_PASSWORD: "aloha"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
  db-data: